### ISSUE TITLE
Writing a protocol other than irc

### ISSUE THREAD

**Issue by TurBoss** [Cadair/python-appservice-framework#1]
Hello:

I'm willing to write a appservice for a game server lobby (SpringRTS)
I would like to help develop this project as I ee it has a lot of potential
but I'm pretty lost :D is there a room where we can talk?

Thanks

edit: what I need is a transparent bridging from matrix to springrts ( not behind a bot (I already have this))

**Comment by Cadair** [comment]
For anyone else coming across this, there is now a room for this project [#pythonappservices:matrix.org](https://matrix.to/#/#pythonappservices:matrix.org)

The purpose of this project is to provide an easy way to write appservice bridges for all protocols.
